//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ORDER_DELIVERY = new HashSet<ORDER_DELIVERY>();
            this.ORDER_SOFRA = new HashSet<ORDER_SOFRA>();
            this.ORDER_TECAYE = new HashSet<ORDER_TECAYE>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string EMPLOYEE_PHONE { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> id_Type_EMPLOYEE { get; set; }
    
        public virtual LoginPage LoginPage { get; set; }
        public virtual Type_EMPLOYEE Type_EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DELIVERY> ORDER_DELIVERY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_SOFRA> ORDER_SOFRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_TECAYE> ORDER_TECAYE { get; set; }
    }
}
