//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DELIVERY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER_DELIVERY()
        {
            this.Stok_ORDER_DELIVERY = new HashSet<Stok_ORDER_DELIVERY>();
        }
    
        public int ID_ORDER_Delivery { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public Nullable<int> Namber_Order_Delivery { get; set; }
        public string Date_Order_Delivery { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<decimal> Total_All { get; set; }
        public Nullable<double> Tax { get; set; }
        public string type_order { get; set; }
        public string Name_Pilot { get; set; }
        public Nullable<bool> Confirmation { get; set; }
        public Nullable<int> Num_Day { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual Table_two_days Table_two_days { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stok_ORDER_DELIVERY> Stok_ORDER_DELIVERY { get; set; }
    }
}
